# Generated by Django 3.0.5 on 2023-05-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_productview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='user',
        ),
    ]
